name: flutter_buffs
description: A new Flutter package project.
version: 0.2.0
homepage: https://github.com/danielwii/flutter-buffs
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  event_bus: ^2.0.0
  dio: ^5.0.3
#  dio_http_cache: ^0.3.0
#  dio_http_cache_lts: ^0.4.0
  url_launcher: ^6.1.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
#  meta: ^1.8.0
  json_serializable: ">=6.3.0"
  json_annotation: ">=4.6.0"
  quiver: ^3.2.1
  supercharged: ^2.1.1
  package_info_plus: ^3.0.2
#  http: ^0.13.4
#  commons: ^0.7.8+3
  fluttertoast: ^8.1.2
  flutter_secure_storage: ^7.0.1
  simple_logger: ^1.9.0+1
  fluttericon: ^2.0.0
  like_button: ^2.0.5
  cached_network_image: ^3.2.3
  extended_text: ^9.1.2
  simple_animations: ^5.0.0+3
  flukit: ^3.0.1
  flutter_cache_manager: ^3.3.0
  flutter_spinkit: ^5.1.0
  flutter_blurhash: ^0.7.0

dev_dependencies:
#  flutter_test:
#    sdk: flutter

  hive_generator: ^2.0.0
  flutter_lints: ">=2.0.0"
  build_runner: ">=2.2.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
