name: flutter_buffs
description: A new Flutter package project.
version: 0.2.0
homepage:
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"

dependency_overrides:
  flutter_blurhash: ^0.7.0

dependencies:
  flutter:
    sdk: flutter
#  event_bus: ^2.0.0
  dio: ^4.0.6
#  dio_http_cache: ^0.3.0
#  dio_http_cache_lts: ^0.4.0
  url_launcher: ^6.1.2
  meta: ^1.3.0-nullsafety.3
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  quiver: ^3.1.0
  supercharged: ^2.1.1
#  http: ^0.13.4
#  commons: ^0.7.8+3
  fluttertoast: ^8.0.9
  flutter_secure_storage: ^5.0.2
  simple_logger: ^1.9.0
  fluttericon: ^2.0.0
  like_button: ^2.0.4
  cached_network_image: ^3.2.0
  extended_text: ^9.1.0
  simple_animations: ^4.0.2
  flukit: ^2.0.0
  flutter_cache_manager: ^3.3.0
  flutter_spinkit: ^5.1.0
  flutter_blurhash: ^0.7.0

dev_dependencies:
#  flutter_test:
#    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.1.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
